// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eProtokoll.Data;

#nullable disable

namespace eProtokoll.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260107151157_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("eProtokoll.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime?>("ModifiedData")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("eProtokoll.Models.Classification", b =>
                {
                    b.Property<int>("ClassificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassificationId"));

                    b.Property<bool>("AllowCopy")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowDownload")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowPrint")
                        .HasColumnType("bit");

                    b.Property<string>("ColorCode")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EnableAuditLog")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("MinimumRoleRequired")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("bit");

                    b.Property<int>("RetentionYears")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ClassificationId");

                    b.HasIndex("Level");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Classifications");

                    b.HasData(
                        new
                        {
                            ClassificationId = 1,
                            AllowCopy = true,
                            AllowDownload = true,
                            AllowPrint = true,
                            ColorCode = "#28a745",
                            CreatedDate = new DateTime(2026, 1, 7, 16, 11, 55, 780, DateTimeKind.Local).AddTicks(2019),
                            Description = "Dokumente publike që mund të shihen nga të gjithë",
                            EnableAuditLog = true,
                            IsActive = true,
                            IsDefault = true,
                            Level = 1,
                            Name = "Publik",
                            RequiresApproval = false,
                            RetentionYears = 5,
                            SortOrder = 1
                        },
                        new
                        {
                            ClassificationId = 2,
                            AllowCopy = true,
                            AllowDownload = true,
                            AllowPrint = true,
                            ColorCode = "#17a2b8",
                            CreatedDate = new DateTime(2026, 1, 7, 16, 11, 55, 780, DateTimeKind.Local).AddTicks(2058),
                            Description = "Vetëm për punonjësit e autorizuar (assigned)",
                            EnableAuditLog = true,
                            IsActive = true,
                            IsDefault = false,
                            Level = 2,
                            Name = "I kufizuar",
                            RequiresApproval = false,
                            RetentionYears = 10,
                            SortOrder = 2
                        },
                        new
                        {
                            ClassificationId = 3,
                            AllowCopy = false,
                            AllowDownload = false,
                            AllowPrint = false,
                            ColorCode = "#fd7e14",
                            CreatedDate = new DateTime(2026, 1, 7, 16, 11, 55, 780, DateTimeKind.Local).AddTicks(2070),
                            Description = "Vetëm menaxherët dhe administratorët",
                            EnableAuditLog = true,
                            IsActive = true,
                            IsDefault = false,
                            Level = 3,
                            Name = "Sekret",
                            RequiresApproval = true,
                            RetentionYears = 20,
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("eProtokoll.Models.Deadline", b =>
                {
                    b.Property<int>("DeadlineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeadlineId"));

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AutoEscalate")
                        .HasColumnType("bit");

                    b.Property<string>("CompletedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompletionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("DueTime")
                        .HasColumnType("time");

                    b.Property<int>("EscalateDaysBefore")
                        .HasColumnType("int");

                    b.Property<string>("EscalateToUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("EscalatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtendedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ExtensionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtensionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEscalated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExtended")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastReminderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NotificationDaysBefore")
                        .HasColumnType("int");

                    b.Property<bool>("NotificationSent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NotificationSentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OriginalDueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("int");

                    b.Property<int>("ReminderCount")
                        .HasColumnType("int");

                    b.Property<int>("ReminderIntervalDays")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("bit");

                    b.Property<string>("ResponsibleDepartment")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResponsibleUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("SendNotification")
                        .HasColumnType("bit");

                    b.Property<bool>("SendReminder")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("DeadlineId");

                    b.HasIndex("CompletedBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DocumentId");

                    b.HasIndex("DueDate");

                    b.HasIndex("EscalateToUserId");

                    b.HasIndex("ResponsibleUserId");

                    b.HasIndex("Status");

                    b.ToTable("Deadlines");
                });

            modelBuilder.Entity("eProtokoll.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<string>("ArchivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArchivedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClassificationId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeadlineDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<bool>("HasAttachments")
                        .HasColumnType("bit");

                    b.Property<bool>("HasDeadline")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsScanned")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProtocolDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProtocolNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("ProtocolTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("ReferenceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("DocumentId");

                    b.HasIndex("ClassificationId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DocumentType");

                    b.HasIndex("ProtocolDate");

                    b.HasIndex("ProtocolNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Documents");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Document");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("eProtokoll.Models.DocumentAttachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<bool>("AllowDownload")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowPrint")
                        .HasColumnType("bit");

                    b.Property<string>("AntivirusEngine")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ArchivedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("int");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileExtension")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FileHash")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("HasOCR")
                        .HasColumnType("bit");

                    b.Property<bool>("HasThumbnail")
                        .HasColumnType("bit");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompressed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDownloaded")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimaryDocument")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrinted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsScanned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVirusFree")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVirusScanned")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastDownloadedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastPrintedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastViewedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metadata")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("OCRProcessedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OCRText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<int?>("PreviousVersionId")
                        .HasColumnType("int");

                    b.Property<int>("PrintCount")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresAuthorization")
                        .HasColumnType("bit");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VirusScanDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("AttachmentId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("FileHash");

                    b.HasIndex("PreviousVersionId");

                    b.HasIndex("UploadedBy");

                    b.HasIndex("UploadedDate");

                    b.ToTable("DocumentAttachments");
                });

            modelBuilder.Entity("eProtokoll.Models.DocumentTracking", b =>
                {
                    b.Property<int>("TrackingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackingId"));

                    b.Property<DateTime?>("AcceptedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<string>("AssignedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("AssignedTime")
                        .HasColumnType("time");

                    b.Property<string>("AssignedToUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AttachedFiles")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompletionComment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("CompletionPercentage")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DelegatedToTrackingId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DurationHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HasDeadline")
                        .HasColumnType("bit");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelegated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInProgress")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOverdue")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRejected")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ParentTrackingId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RejectedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("RequiresReport")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresResponse")
                        .HasColumnType("bit");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("TrackingId");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("DelegatedToTrackingId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("DueDate");

                    b.HasIndex("ParentTrackingId");

                    b.HasIndex("Status");

                    b.ToTable("DocumentTrackings");
                });

            modelBuilder.Entity("eProtokoll.Models.Institution", b =>
                {
                    b.Property<int>("InstitutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstitutionId"));

                    b.Property<string>("Adress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContactPosition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Fax")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("InstitutionId");

                    b.HasIndex("Name");

                    b.HasIndex("TaxCode")
                        .IsUnique()
                        .HasFilter("[TaxCode] IS NOT NULL");

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("eProtokoll.Models.ProtocolSettings", b =>
                {
                    b.Property<int>("ProtocolSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProtocolSettingsId"));

                    b.Property<bool>("AllowManualEdit")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoResetYearly")
                        .HasColumnType("bit");

                    b.Property<string>("ClosedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FiscalYearEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FiscalYearStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("IncomingCurrentNumber")
                        .HasColumnType("int");

                    b.Property<int?>("IncomingEndNumber")
                        .HasColumnType("int");

                    b.Property<string>("IncomingPrefix")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IncomingStartNumber")
                        .HasColumnType("int");

                    b.Property<string>("IncomingSuffix")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("InstitutionAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InstitutionCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InstitutionEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InstitutionName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("InstitutionPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("InstitutionWebsite")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("InternalCurrentNumber")
                        .HasColumnType("int");

                    b.Property<int?>("InternalEndNumber")
                        .HasColumnType("int");

                    b.Property<string>("InternalPrefix")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("InternalStartNumber")
                        .HasColumnType("int");

                    b.Property<string>("InternalSuffix")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NumberPadding")
                        .HasColumnType("int");

                    b.Property<int>("OutgoingCurrentNumber")
                        .HasColumnType("int");

                    b.Property<int?>("OutgoingEndNumber")
                        .HasColumnType("int");

                    b.Property<string>("OutgoingPrefix")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("OutgoingStartNumber")
                        .HasColumnType("int");

                    b.Property<string>("OutgoingSuffix")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProtocolNumberFormat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("ShowYearInNumber")
                        .HasColumnType("bit");

                    b.Property<bool>("UseSeparatorSlash")
                        .HasColumnType("bit");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ProtocolSettingsId");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("ProtocolSettings");

                    b.HasData(
                        new
                        {
                            ProtocolSettingsId = 1,
                            AllowManualEdit = false,
                            AutoResetYearly = true,
                            CreatedDate = new DateTime(2026, 1, 7, 16, 11, 55, 780, DateTimeKind.Local).AddTicks(2657),
                            IncomingCurrentNumber = 1,
                            IncomingPrefix = "H",
                            IncomingStartNumber = 1,
                            InternalCurrentNumber = 1,
                            InternalPrefix = "B",
                            InternalStartNumber = 1,
                            IsActive = true,
                            IsClosed = false,
                            NumberPadding = 4,
                            OutgoingCurrentNumber = 1,
                            OutgoingPrefix = "D",
                            OutgoingStartNumber = 1,
                            ProtocolNumberFormat = "{PREFIX}-{NUMBER}/{YEAR}",
                            ShowYearInNumber = true,
                            UseSeparatorSlash = true,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("eProtokoll.Models.IncomingDocument", b =>
                {
                    b.HasBaseType("eProtokoll.Models.Document");

                    b.Property<DateTime?>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DeliveryMethod")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EnvelopeNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasPhysicalCopy")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSeal")
                        .HasColumnType("bit");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsConfidential")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOriginal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsResponded")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OriginalDocumentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginalDocumentNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhysicalLocation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReceivedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("ReceivedTime")
                        .HasColumnType("time");

                    b.Property<bool>("RequiresResponse")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResponseDeadline")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ResponseDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("SenderEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SenderPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SenderPosition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("ReceivedBy");

                    b.HasIndex("ReceivedDate");

                    b.HasDiscriminator().HasValue("IncomingDocument");
                });

            modelBuilder.Entity("eProtokoll.Models.InternalDocument", b =>
                {
                    b.HasBaseType("eProtokoll.Models.Document");

                    b.Property<bool>("ActionCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ActionCompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActionRequired")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ApprovalComment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CarbonCopyList")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CirculationList")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("CirculationOrder")
                        .HasColumnType("int");

                    b.Property<string>("FromDepartment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FromUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("HasDigitalSignature")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPhysicalCopy")
                        .HasColumnType("bit");

                    b.Property<string>("InternalReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("InternalType")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCirculation")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConfidential")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<bool>("IsResponded")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfCopies")
                        .HasColumnType("int");

                    b.Property<string>("PhysicalLocation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReadBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RelatedDocumentId")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresAttention")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresResponse")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresSignature")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResponseDeadline")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ResponseDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("SignedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("SignedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToDepartment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ToUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("FromDepartment");

                    b.HasIndex("FromUserId");

                    b.HasIndex("RelatedDocumentId");

                    b.HasIndex("ResponseDocumentId");

                    b.HasIndex("SignedBy");

                    b.HasIndex("ToDepartment");

                    b.HasIndex("ToUserId");

                    b.ToTable("Documents", t =>
                        {
                            t.Property("HasPhysicalCopy")
                                .HasColumnName("InternalDocument_HasPhysicalCopy");

                            t.Property("IsConfidential")
                                .HasColumnName("InternalDocument_IsConfidential");

                            t.Property("IsResponded")
                                .HasColumnName("InternalDocument_IsResponded");

                            t.Property("PhysicalLocation")
                                .HasColumnName("InternalDocument_PhysicalLocation");

                            t.Property("RequiresResponse")
                                .HasColumnName("InternalDocument_RequiresResponse");

                            t.Property("ResponseDate")
                                .HasColumnName("InternalDocument_ResponseDate");

                            t.Property("ResponseDeadline")
                                .HasColumnName("InternalDocument_ResponseDeadline");

                            t.Property("ResponseDocumentId")
                                .HasColumnName("InternalDocument_ResponseDocumentId");
                        });

                    b.HasDiscriminator().HasValue("InternalDocument");
                });

            modelBuilder.Entity("eProtokoll.Models.OutgoingDocument", b =>
                {
                    b.HasBaseType("eProtokoll.Models.Document");

                    b.Property<string>("ArchiveLocation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CarbonCopyList")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ConfirmationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConfirmedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DeliveryMethod")
                        .HasColumnType("int");

                    b.Property<bool>("HasArchiveCopy")
                        .HasColumnType("bit");

                    b.Property<bool>("HasDigitalSignature")
                        .HasColumnType("bit");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeliveryConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsResponse")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSealed")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfCopies")
                        .HasColumnType("int");

                    b.Property<int?>("OriginalIncomingDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("PreparedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("PreparedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecipientAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RecipientEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RecipientPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RecipientPosition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RequiresDeliveryConfirmation")
                        .HasColumnType("bit");

                    b.Property<string>("SentBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("SentTime")
                        .HasColumnType("time");

                    b.Property<string>("ShipmentCompany")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("ShipmentCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShipmentNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ShipmentStatus")
                        .HasColumnType("int");

                    b.Property<string>("SignedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("SignedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SignerPosition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("OriginalIncomingDocumentId")
                        .IsUnique()
                        .HasFilter("[OriginalIncomingDocumentId] IS NOT NULL");

                    b.HasIndex("PreparedBy");

                    b.HasIndex("SentBy");

                    b.HasIndex("SentDate");

                    b.ToTable("Documents", t =>
                        {
                            t.Property("CarbonCopyList")
                                .HasColumnName("OutgoingDocument_CarbonCopyList");

                            t.Property("DeliveryMethod")
                                .HasColumnName("OutgoingDocument_DeliveryMethod");

                            t.Property("HasDigitalSignature")
                                .HasColumnName("OutgoingDocument_HasDigitalSignature");

                            t.Property("InstitutionId")
                                .HasColumnName("OutgoingDocument_InstitutionId");

                            t.Property("NumberOfCopies")
                                .HasColumnName("OutgoingDocument_NumberOfCopies");

                            t.Property("SignedBy")
                                .HasColumnName("OutgoingDocument_SignedBy");

                            t.Property("SignedDate")
                                .HasColumnName("OutgoingDocument_SignedDate");
                        });

                    b.HasDiscriminator().HasValue("OutgoingDocument");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("eProtokoll.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("eProtokoll.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eProtokoll.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("eProtokoll.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eProtokoll.Models.Deadline", b =>
                {
                    b.HasOne("eProtokoll.Models.ApplicationUser", "CompletedByUser")
                        .WithMany()
                        .HasForeignKey("CompletedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eProtokoll.Models.ApplicationUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eProtokoll.Models.Document", "Document")
                        .WithMany("Deadlines")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eProtokoll.Models.ApplicationUser", "EscalateToUser")
                        .WithMany()
                        .HasForeignKey("EscalateToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eProtokoll.Models.ApplicationUser", "ResponsibleUser")
                        .WithMany("Deadlines")
                        .HasForeignKey("ResponsibleUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CompletedByUser");

                    b.Navigation("Creator");

                    b.Navigation("Document");

                    b.Navigation("EscalateToUser");

                    b.Navigation("ResponsibleUser");
                });

            modelBuilder.Entity("eProtokoll.Models.Document", b =>
                {
                    b.HasOne("eProtokoll.Models.Classification", "Classification")
                        .WithMany("Documents")
                        .HasForeignKey("ClassificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eProtokoll.Models.ApplicationUser", "Creator")
                        .WithMany("CreatedDocuments")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classification");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("eProtokoll.Models.DocumentAttachment", b =>
                {
                    b.HasOne("eProtokoll.Models.Document", "Document")
                        .WithMany("Attachments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eProtokoll.Models.DocumentAttachment", "PreviousVersion")
                        .WithMany("Versions")
                        .HasForeignKey("PreviousVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eProtokoll.Models.ApplicationUser", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("PreviousVersion");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("eProtokoll.Models.DocumentTracking", b =>
                {
                    b.HasOne("eProtokoll.Models.ApplicationUser", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eProtokoll.Models.ApplicationUser", "AssignedToUser")
                        .WithMany("AssignedDocuments")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eProtokoll.Models.DocumentTracking", "DelegatedToTracking")
                        .WithMany()
                        .HasForeignKey("DelegatedToTrackingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eProtokoll.Models.Document", "Document")
                        .WithMany("Trackings")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eProtokoll.Models.DocumentTracking", "ParentTracking")
                        .WithMany("SubDelegations")
                        .HasForeignKey("ParentTrackingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedByUser");

                    b.Navigation("AssignedToUser");

                    b.Navigation("DelegatedToTracking");

                    b.Navigation("Document");

                    b.Navigation("ParentTracking");
                });

            modelBuilder.Entity("eProtokoll.Models.IncomingDocument", b =>
                {
                    b.HasOne("eProtokoll.Models.ApplicationUser", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedTo");

                    b.HasOne("eProtokoll.Models.Institution", "Institution")
                        .WithMany("IncomingDocuments")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eProtokoll.Models.ApplicationUser", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceivedBy");

                    b.Navigation("AssignedUser");

                    b.Navigation("Institution");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("eProtokoll.Models.InternalDocument", b =>
                {
                    b.HasOne("eProtokoll.Models.ApplicationUser", "Approver")
                        .WithMany()
                        .HasForeignKey("ApprovedBy");

                    b.HasOne("eProtokoll.Models.ApplicationUser", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId");

                    b.HasOne("eProtokoll.Models.InternalDocument", "RelatedDocument")
                        .WithMany()
                        .HasForeignKey("RelatedDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eProtokoll.Models.InternalDocument", "ResponseDocument")
                        .WithMany()
                        .HasForeignKey("ResponseDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eProtokoll.Models.ApplicationUser", "Signer")
                        .WithMany()
                        .HasForeignKey("SignedBy");

                    b.HasOne("eProtokoll.Models.ApplicationUser", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId");

                    b.Navigation("Approver");

                    b.Navigation("FromUser");

                    b.Navigation("RelatedDocument");

                    b.Navigation("ResponseDocument");

                    b.Navigation("Signer");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("eProtokoll.Models.OutgoingDocument", b =>
                {
                    b.HasOne("eProtokoll.Models.Institution", "Institution")
                        .WithMany("OutgoingDocuments")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eProtokoll.Models.IncomingDocument", "OriginalIncomingDocument")
                        .WithOne("ResponseDocument")
                        .HasForeignKey("eProtokoll.Models.OutgoingDocument", "OriginalIncomingDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eProtokoll.Models.ApplicationUser", "Preparer")
                        .WithMany()
                        .HasForeignKey("PreparedBy");

                    b.HasOne("eProtokoll.Models.ApplicationUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SentBy");

                    b.Navigation("Institution");

                    b.Navigation("OriginalIncomingDocument");

                    b.Navigation("Preparer");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("eProtokoll.Models.ApplicationUser", b =>
                {
                    b.Navigation("AssignedDocuments");

                    b.Navigation("CreatedDocuments");

                    b.Navigation("Deadlines");
                });

            modelBuilder.Entity("eProtokoll.Models.Classification", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("eProtokoll.Models.Document", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Deadlines");

                    b.Navigation("Trackings");
                });

            modelBuilder.Entity("eProtokoll.Models.DocumentAttachment", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("eProtokoll.Models.DocumentTracking", b =>
                {
                    b.Navigation("SubDelegations");
                });

            modelBuilder.Entity("eProtokoll.Models.Institution", b =>
                {
                    b.Navigation("IncomingDocuments");

                    b.Navigation("OutgoingDocuments");
                });

            modelBuilder.Entity("eProtokoll.Models.IncomingDocument", b =>
                {
                    b.Navigation("ResponseDocument");
                });
#pragma warning restore 612, 618
        }
    }
}
