// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eProtokoll.Data;

#nullable disable

namespace eProtokoll.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260313131254_AuditLogTable")]
    partial class AuditLogTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eProtokoll.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<int>("Classification")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<bool>("HasAttachments")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProtocolDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProtocolNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("ProtocolTime")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("DocumentId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DocumentType");

                    b.HasIndex("ProtocolDate");

                    b.HasIndex("ProtocolNumber")
                        .IsUnique();

                    b.ToTable("Documents");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Document");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("eProtokoll.Models.DocumentAttachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("FileExtension")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPrimaryDocument")
                        .HasColumnType("bit");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AttachmentId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("UploadedBy");

                    b.HasIndex("UploadedDate");

                    b.ToTable("DocumentAttachments");
                });

            modelBuilder.Entity("eProtokoll.Models.DocumentPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("UserId");

                    b.ToTable("DocumentPermissions");
                });

            modelBuilder.Entity("eProtokoll.Models.DocumentTracking", b =>
                {
                    b.Property<int>("TrackingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackingId"));

                    b.Property<int>("AssignedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int?>("DocumentId1")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("TrackingId");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("DocumentId1");

                    b.HasIndex("DueDate");

                    b.ToTable("DocumentTrackings");
                });

            modelBuilder.Entity("eProtokoll.Models.Institution", b =>
                {
                    b.Property<int>("InstitutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstitutionId"));

                    b.Property<string>("Adress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContactPosition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Fax")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("InstitutionId");

                    b.HasIndex("Name");

                    b.HasIndex("TaxCode")
                        .IsUnique()
                        .HasFilter("[TaxCode] IS NOT NULL");

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("eProtokoll.Models.ProtocolSettings", b =>
                {
                    b.Property<int>("ProtocolSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProtocolSettingsId"));

                    b.Property<bool>("AllowManualEdit")
                        .HasColumnType("bit");

                    b.Property<bool>("AutoResetYearly")
                        .HasColumnType("bit");

                    b.Property<string>("ClosedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FiscalYearEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FiscalYearStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("IncomingCurrentNumber")
                        .HasColumnType("int");

                    b.Property<int?>("IncomingEndNumber")
                        .HasColumnType("int");

                    b.Property<string>("IncomingPrefix")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IncomingStartNumber")
                        .HasColumnType("int");

                    b.Property<string>("IncomingSuffix")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("InstitutionAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InstitutionCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InstitutionEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InstitutionName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("InstitutionPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("InstitutionWebsite")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("InternalCurrentNumber")
                        .HasColumnType("int");

                    b.Property<int?>("InternalEndNumber")
                        .HasColumnType("int");

                    b.Property<string>("InternalPrefix")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("InternalStartNumber")
                        .HasColumnType("int");

                    b.Property<string>("InternalSuffix")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NumberPadding")
                        .HasColumnType("int");

                    b.Property<int>("OutgoingCurrentNumber")
                        .HasColumnType("int");

                    b.Property<int?>("OutgoingEndNumber")
                        .HasColumnType("int");

                    b.Property<string>("OutgoingPrefix")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("OutgoingStartNumber")
                        .HasColumnType("int");

                    b.Property<string>("OutgoingSuffix")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProtocolNumberFormat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("ShowYearInNumber")
                        .HasColumnType("bit");

                    b.Property<bool>("UseSeparatorSlash")
                        .HasColumnType("bit");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ProtocolSettingsId");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("ProtocolSettings");

                    b.HasData(
                        new
                        {
                            ProtocolSettingsId = 1,
                            AllowManualEdit = false,
                            AutoResetYearly = true,
                            CreatedDate = new DateTime(2026, 3, 13, 14, 12, 53, 325, DateTimeKind.Local).AddTicks(1712),
                            IncomingCurrentNumber = 1,
                            IncomingPrefix = "H",
                            IncomingStartNumber = 1,
                            InternalCurrentNumber = 1,
                            InternalPrefix = "B",
                            InternalStartNumber = 1,
                            IsActive = true,
                            IsClosed = false,
                            NumberPadding = 4,
                            OutgoingCurrentNumber = 1,
                            OutgoingPrefix = "D",
                            OutgoingStartNumber = 1,
                            ProtocolNumberFormat = "{PREFIX}-{NUMBER}/{YEAR}",
                            ShowYearInNumber = true,
                            UseSeparatorSlash = true,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("eProtokoll.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("eProtokoll.Models.IncomingDocument", b =>
                {
                    b.HasBaseType("eProtokoll.Models.Document");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsResponded")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OriginalDocumentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginalDocumentNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ReceivedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResponseDeadline")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ResponseDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("ReceivedBy");

                    b.HasIndex("ReceivedDate");

                    b.HasIndex("ResponseDocumentId")
                        .IsUnique()
                        .HasFilter("[ResponseDocumentId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("IncomingDocument");
                });

            modelBuilder.Entity("eProtokoll.Models.InternalDocument", b =>
                {
                    b.HasBaseType("eProtokoll.Models.Document");

                    b.Property<string>("FromDepartment")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ResponseDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("ToDepartment")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasIndex("FromDepartment");

                    b.HasIndex("ResponseDocumentId");

                    b.HasIndex("ToDepartment");

                    b.ToTable("Documents", t =>
                        {
                            t.Property("ResponseDocumentId")
                                .HasColumnName("InternalDocument_ResponseDocumentId");
                        });

                    b.HasDiscriminator().HasValue("InternalDocument");
                });

            modelBuilder.Entity("eProtokoll.Models.OutgoingDocument", b =>
                {
                    b.HasBaseType("eProtokoll.Models.Document");

                    b.Property<string>("ArchiveLocation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsResponse")
                        .HasColumnType("bit");

                    b.Property<int?>("OriginalIncomingDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasIndex("InstitutionId");

                    b.ToTable("Documents", t =>
                        {
                            t.Property("InstitutionId")
                                .HasColumnName("OutgoingDocument_InstitutionId");
                        });

                    b.HasDiscriminator().HasValue("OutgoingDocument");
                });

            modelBuilder.Entity("eProtokoll.Models.Document", b =>
                {
                    b.HasOne("eProtokoll.Models.Users", "Creator")
                        .WithMany("CreatedDocuments")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("eProtokoll.Models.DocumentAttachment", b =>
                {
                    b.HasOne("eProtokoll.Models.Document", "Document")
                        .WithMany("Attachments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eProtokoll.Models.Users", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("eProtokoll.Models.DocumentPermission", b =>
                {
                    b.HasOne("eProtokoll.Models.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eProtokoll.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eProtokoll.Models.DocumentTracking", b =>
                {
                    b.HasOne("eProtokoll.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eProtokoll.Models.Users", null)
                        .WithMany("AssignedDocuments")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eProtokoll.Models.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eProtokoll.Models.Document", null)
                        .WithMany("Trackings")
                        .HasForeignKey("DocumentId1");
                });

            modelBuilder.Entity("eProtokoll.Models.IncomingDocument", b =>
                {
                    b.HasOne("eProtokoll.Models.Institution", "Institution")
                        .WithMany("IncomingDocuments")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eProtokoll.Models.Users", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceivedBy");

                    b.HasOne("eProtokoll.Models.OutgoingDocument", "ResponseDocument")
                        .WithOne("OriginalIncomingDocument")
                        .HasForeignKey("eProtokoll.Models.IncomingDocument", "ResponseDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Institution");

                    b.Navigation("Receiver");

                    b.Navigation("ResponseDocument");
                });

            modelBuilder.Entity("eProtokoll.Models.InternalDocument", b =>
                {
                    b.HasOne("eProtokoll.Models.InternalDocument", "ResponseDocument")
                        .WithMany()
                        .HasForeignKey("ResponseDocumentId");

                    b.Navigation("ResponseDocument");
                });

            modelBuilder.Entity("eProtokoll.Models.OutgoingDocument", b =>
                {
                    b.HasOne("eProtokoll.Models.Institution", "Institution")
                        .WithMany("OutgoingDocuments")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("eProtokoll.Models.Document", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Trackings");
                });

            modelBuilder.Entity("eProtokoll.Models.Institution", b =>
                {
                    b.Navigation("IncomingDocuments");

                    b.Navigation("OutgoingDocuments");
                });

            modelBuilder.Entity("eProtokoll.Models.Users", b =>
                {
                    b.Navigation("AssignedDocuments");

                    b.Navigation("CreatedDocuments");
                });

            modelBuilder.Entity("eProtokoll.Models.OutgoingDocument", b =>
                {
                    b.Navigation("OriginalIncomingDocument");
                });
#pragma warning restore 612, 618
        }
    }
}
